[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "rex-pycli"
version = "1.0.0"
description = "Rex CLI"
requires-python = ">=3.13"

[tool.maturin]

module-name = "rex"

manifest-path = "cli/Cargo.toml"

[tool.maturin.scripts]
rex = "rex"
