[project]
name = "rex"
version = "0.9"

requires-python = ">=3.12"
[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "rex"